name: Build Rethink F-Droid APK

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Gradle
        uses: gradle/gradle-build-action@v2
        with:
           cache-disabled: true

      - name: Build F-Droid Release APK
        run: ./gradlew assembleFdroidFullRelease

      - name: Create output folder
        run: mkdir -p app/build/outputs/apk/fdroidFull/release

      - name: Upload release APK
        uses: actions/upload-artifact@v4
        with:
          name: rethink-fdroid-release
          path: app/build/outputs/apk/fdroidFull/release/*.apk

      - name: List APK files
        run: find app/build -type f -name "*.apk"

      
